import React from "react";
import ReactMarkdown from "react-markdown";
import { LessonResponse, LessonParams } from "../services/gemini";

interface Props {
  lesson: LessonResponse;
  params: LessonParams;
  idPrefix: string;
}

export const LessonExportTemplate: React.FC<Props> = ({ lesson, params, idPrefix }) => {
  // A4 dimensions in pixels at 96 DPI: 794 x 1123
  const pageStyle = {
    width: "794px",
    height: "1123px", // Fixed height for true "pages"
    padding: "80px", // Increased padding for better readability
    backgroundColor: "white",
    color: "#141414",
    position: "relative" as const,
    marginBottom: "40px",
    overflow: "hidden" as const,
  };

  // Helper to split content roughly in half at a newline
  const splitContent = (text: string) => {
    if (!text) return ["", ""];
    const mid = Math.floor(text.length / 2);
    const splitIdx = text.indexOf("\n\n", mid);
    if (splitIdx === -1) {
      const secondTry = text.indexOf("\n", mid);
      if (secondTry === -1) return [text, ""];
      return [text.substring(0, secondTry), text.substring(secondTry)];
    }
    return [text.substring(0, splitIdx), text.substring(splitIdx)];
  };

  const [tg1, tg2] = splitContent(lesson.teacherGuide);
  const [sp1, sp2] = splitContent(lesson.studentPacket);

  return (
    <div id={`${idPrefix}-container`} style={{ position: "absolute", left: "-9999px", top: 0 }}>
      {/* Page 1: Cover */}
      <div id={`${idPrefix}-page-0`} style={pageStyle} className="flex flex-col">
        {lesson.coverImageBase64 && (
          <div className="mb-12">
            <img 
              src={`data:image/png;base64,${lesson.coverImageBase64}`} 
              alt="Cover" 
              className="w-full aspect-video object-cover rounded-sm"
            />
          </div>
        )}
        <h1 className="text-5xl font-serif italic font-bold mb-8">{params.language} {params.level} Lesson</h1>
        <div className="space-y-4 text-xl" style={{ color: "#3730a3" }}>
          <p><strong>Language:</strong> {params.language}</p>
          <p><strong>Level:</strong> {params.level}</p>
          <p><strong>ACTFL Mode:</strong> {params.actflMode}</p>
          <p><strong>Primary Skill:</strong> {params.skill}</p>
          {params.stateStandards && <p><strong>State Standards:</strong> {params.stateStandards}</p>}
          <p className="italic mt-8" style={{ color: "#1e1b4b" }}><strong>Theme:</strong> {params.theme}</p>
        </div>
        <div className="mt-auto pt-12 border-t border-indigo-100 text-sm font-mono uppercase tracking-widest" style={{ color: "#a5b4fc" }}>
          Generated by CL Lengua Gen
        </div>
      </div>

      {/* Page 2: Teacher Guide P1 */}
      <div id={`${idPrefix}-page-1`} style={pageStyle}>
        <h2 className="text-2xl font-serif italic font-bold border-b border-indigo-600 pb-4 mb-8 uppercase tracking-tight text-indigo-900">Teacher Guide (1/2)</h2>
        <div className="export-prose">
          <ReactMarkdown>{tg1}</ReactMarkdown>
        </div>
      </div>

      {/* Page 3: Teacher Guide P2 */}
      <div id={`${idPrefix}-page-2`} style={pageStyle}>
        <h2 className="text-2xl font-serif italic font-bold border-b border-indigo-600 pb-4 mb-8 uppercase tracking-tight text-indigo-900">Teacher Guide (2/2)</h2>
        <div className="export-prose">
          <ReactMarkdown>{tg2}</ReactMarkdown>
        </div>
      </div>

      {/* Page 4: Student Packet P1 */}
      <div id={`${idPrefix}-page-3`} style={pageStyle}>
        <div className="flex justify-between items-end mb-8 border-b border-indigo-600 pb-4">
          <h2 className="text-xl font-serif italic font-bold uppercase tracking-tight text-indigo-900">Student Packet (1/2)</h2>
          <div className="flex gap-8 text-sm font-mono text-indigo-300">
            <span>Name: __________________________</span>
            <span>Date: ___________</span>
          </div>
        </div>
        <div className="export-prose student">
          <ReactMarkdown>{sp1}</ReactMarkdown>
        </div>
      </div>

      {/* Page 5: Student Packet P2 */}
      <div id={`${idPrefix}-page-4`} style={pageStyle}>
        <div className="flex justify-between items-end mb-8 border-b border-indigo-600 pb-4">
          <h2 className="text-xl font-serif italic font-bold uppercase tracking-tight text-indigo-900">Student Packet (2/2)</h2>
          <div className="flex gap-8 text-sm font-mono text-indigo-300">
            <span>Name: __________________________</span>
            <span>Date: ___________</span>
          </div>
        </div>
        <div className="export-prose student">
          <ReactMarkdown>{sp2}</ReactMarkdown>
        </div>
      </div>
    </div>
  );
};
